# Generated by Django 3.2.7 on 2021-10-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_auto_20211006_1120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="final_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name="Общая цена"),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="final_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name="Общая цена"),
        ),
    ]
