name: Code checks

on:
  push:
    branches: [master, stage_2]
  pull_request:
    branches: [master, stage_2]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirments.txt
#      - name: Run flake8
#        run: flake8.exe .
#      - name: Run mypy
#        run: mypy.exe .
      - name: Run black
        run: black .

